# 使用 UTF-8 编码，区分大小写
version: ${version}
# 日志
log:
  # 日志存储
  storage:
    enabled: true # 是否开启
    flush_interval: 60 # 刷新缓存间隔，秒
# 丢下掉落物记录
player_drop_record:
  enabled: true # 是否开启
# 捡起掉落物记录
player_pickup_record:
  enabled: true # 是否开启
# 实体清理
clean_entity:
  bossbar:
    color: YELLOW
    style: SOLID
  enabled: true # 是否开启
  interval: 300 # 间隔：秒
  worlds: # 世界正则表达式
    - '.*'
  target:
    includes: # 包含
      '1':
        type: CLASS
        classes:
          - 'Monster'
    excludes: # 除外（优先级高）
      '1':
        type: METADATA
        names:
          - 'MyPet'
          - 'NPC'
      '2':
        type: CUSTOM_NAME
        regexes:
          - '.*'
      '3':
        type: ENUM
        regexes:
          - 'ENDER_DRAGON'
          - 'ZOMBIE_VILLAGER'
  countdown_seconds: 60 # 倒计时，秒
# 清理掉落物
clean_drop:
  bossbar:
    color: YELLOW
    style: SOLID
  enabled: true # 是否开启
  worlds: # 世界正则表达式
    - '.*'
  target:
    includes: # 包含
      '1':
        type: ENUM
        regexes:
          - '.*'
    excludes: # 除外（优先级高）
      '1':
        type: ENCHANTMENT
        regexes:
          - 'DAMAGE_ALL'
          - '.*'
      '2':
        type: CUSTOM_NAME
        regexes:
          - '.*'
      '3':
        type: LORE
        regexes:
          - '.*'
          - '已绑定'
      '4':
        type: ENUM
        regexes:
          - '.*_BOX'
          - 'DIAMOND'
  interval: 300 # 间隔，秒
  countdown_seconds: 60 # 倒计时，秒
# 实体生成间隔限制
entity_spawn_interval_limit:
  enabled: true # 是否开启
  worlds: # 世界正则表达式
    - '.*'
  intervals:
    '1':
      interval: 1000
      target:
        includes: # 包含
          '1':
            type: ENUM
            regexes:
              - 'ZOMBIE'
        excludes: {}
# 区块密集实体清理
anti_entity_farm:
  enabled: true # 是否开启
  check_event: true # 同时检查事件，这会导致区块实体数量到达阈值时无法使用生成蛋等方式生成
  interval: 15   # 检测间隔，秒
  worlds: # 世界正则表达式
    - '.*'
  limits:
    '1':
      threshold: 3
      target:
        includes: # 包含
          '1':
            type: CLASS
            classes:
              - 'Monster'
        excludes: # 除外（优先级高）
          '1':
            type: METADATA
            metadata:
              - 'MyPet'
              - 'NPC'
          '2':
            type: ENUM
            regexes:
              - 'ENDER_DRAGON'
              - 'ZOMBIE_VILLAGER'
          '3':
            type: CUSTOM_NAME
            regexes:
              - '.*'
# QuickShop 偷东西bug修复
quickshop_bug_fix:
  enabled: true # 是否开启
# 禁止非法插件
anti_illegal_player:
  enabled: false # 是否开启
  deop_on_quit: true # 下线就取消OP
  survival_mode_on_quit: true # 下线就设置为生存模式
  creative_whitelist: # 创造模式白名单
    - 'July_ss'
  op_whitelist: # OP 白名单
    - 'July_ss'
# 红石限制
redstone_limit:
  enabled: true # 是否开启
  worlds: # 世界正则表达式
    - '.*'
  tps: 20 # 低于 tps 将启用限制
  duration: 10 # 检测持续时间
  threshold: 6 # 阈值
  ban_duration: 120   # 封禁时间，秒
  notify_interval: 10 # 通知间隔
# 农作物防踩踏
anti_trample_crop:
  enabled: true # 是否开启
# 聊天限制
chat_limit:
  enabled: true # 是否开启
  interval: 3 # # 两次发言间隔，秒
  bad_words: # 正则表达式
    - 'nmsl'
    - '[草操艹]你[吗妈]'
  replace_string: '*' # 替换字符串，
  cancelled: false # 是否直接取消发送
# 自动重启
auto_restart:
  enabled: false
  bossbar:
    color: YELLOW
    style: SOLID
  times: # 24小时制
    - '23:00:00'
  countdown_seconds: 60 # 倒计时时间
  before_commands: # 重启前执行的指令
    - 'save-all'