name: JulySafe
author: July_ss
version: ${version}
main: com.github.julyss2019.bukkit.plugins.julysafe.JulySafe
api-version: 1.13
softdepend:
  - JulyLibrary
  - QuickShop
commands:
  julysafe:
    aliases:
      - jsafe
